#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
E_eng recodification - aggregation and verification script
==========================================================

Reproduces the "Duration of temporal engagement", "Frequency of participatory
activities" and "Both duration and frequency reported" rows of Table 11 of the
mémoire (N = 343).

What this script does and does not do
-------------------------------------
The duration variable is NOT generated by this script. As stated in note (d)
of Table 11, each of the 343 free-text entries of the E_eng field was read
individually and assigned to one of six mutually exclusive categories by a
human coder, giving priority to explicit duration statements over date ranges
mentioned incidentally in the same entry. That case-by-case assignment is the
primary record and is distributed as data:

    E_eng_case_by_case_coding.ods   row_index | category | source_text

This script joins that coding to the extraction dataset, checks that the two
are aligned row by row, recomputes the published counts, and compares them to
the values printed in Table 11. Only the frequency indicator is derived here
by rule, since it depends on a small closed set of periodicity markers.

Inputs (expected in the same directory)
---------------------------------------
    resultats_extraction_clean_V__1_.ods    extraction dataset, header on row 3
    E_eng_case_by_case_coding.ods           case-by-case duration coding

Output
------
    E_eng_recoded.csv   study ID, duration category, frequency indicator
    plus a verification report on stdout (exit code 1 if any count diverges)
"""

import re
import sys
import collections
import pandas as pd

DATASET = "resultats_extraction_clean_V__1_.ods"
CODING = "E_eng_case_by_case_coding.ods"
OUTPUT = "E_eng_recoded.csv"

COL_ENG = "E_eng Temporal engagement (duration + frequency)"
COL_ID = "A1 Study ID: DOI / URL"
N = 343

# Values as printed in Table 11 of the mémoire.
PUBLISHED = {
    "short": 72,
    "intermediate": 62,
    "long": 70,
    "ongoing": 57,
    "single": 23,
    "NR": 59,
}
PUBLISHED_FREQ = 73
PUBLISHED_BOTH = 72

LABELS = {
    "short": "Short (6 months or less)",
    "intermediate": "Intermediate (7 to 24 months)",
    "long": "Long (more than 24 months, bounded)",
    "ongoing": "Ongoing or open-ended",
    "single": "Single episode",
    "NR": "Not reported",
}
ORDER = ["short", "intermediate", "long", "ongoing", "single", "NR"]

# Periodicity markers. A statement that the frequency was not reported
# overrides any marker appearing elsewhere in the same entry.
FREQ = re.compile(
    r"\b(weekly|monthly|bi-?weekly|fortnightly|daily|quarterly|annual|yearly|"
    r"seasonal|twice|per week|per month|per year|every \w+|once a \w+|regular)",
    re.I)
NO_FREQ = re.compile(r"frequency\s*(?:was|is)?\s*not\s*(?:reported|specified|stated)",
                     re.I)


def normalise(series):
    """Whitespace- and case-insensitive form, for the alignment check."""
    return series.astype(str).str.strip().str.replace(r"\s+", " ", regex=True).str.lower()


def main():
    data = pd.read_excel(DATASET, engine="odf", header=2)
    coding = pd.read_excel(CODING, engine="odf").sort_values("row_index")
    coding = coding.reset_index(drop=True)

    if len(data) != N or len(coding) != N:
        sys.exit(f"expected {N} rows in both files; "
                 f"got {len(data)} and {len(coding)}")

    # The coding file carries the source text it was assigned from. Verifying
    # that it still matches the dataset row by row is what makes the join safe:
    # the two files are linked by position, not by a shared key.
    mismatch = (normalise(coding["source_text"]) != normalise(data[COL_ENG]))
    if mismatch.any():
        rows = list(coding.index[mismatch])[:10]
        sys.exit(f"coding file is not aligned with the dataset at rows {rows}")
    print(f"alignment check: {N}/{N} rows match the E_eng source field")

    category = coding["category"].astype(str).str.strip()
    engtext = data[COL_ENG].astype(str)
    frequency = [bool(FREQ.search(v)) and not NO_FREQ.search(v) for v in engtext]

    out = pd.DataFrame({
        "study_id": data[COL_ID].astype(str),
        "duration_category": category,
        "frequency_reported": [int(f) for f in frequency],
    })
    out.to_csv(OUTPUT, index=False)

    counts = collections.Counter(category)
    n_freq = sum(frequency)
    n_both = sum(1 for i, f in enumerate(frequency) if f and category[i] != "NR")

    print("\nDuration of temporal engagement")
    print("-" * 72)
    ok = True
    for key in ORDER:
        obs, pub = counts[key], PUBLISHED[key]
        flag = "ok" if obs == pub else "DIVERGENCE"
        ok &= obs == pub
        print(f"  {LABELS[key]:<38} {obs:>4} {pub:>6}  {flag}")
    print(f"  {'total':<38} {sum(counts.values()):>4} {N:>6}")

    print("\nFrequency of participatory activities")
    print("-" * 72)
    for lab, obs, pub in [("Stated", n_freq, PUBLISHED_FREQ),
                          ("Both duration and frequency", n_both, PUBLISHED_BOTH)]:
        flag = "ok" if obs == pub else f"difference ({obs - pub:+d})"
        print(f"  {lab:<38} {obs:>4} {pub:>6}  {flag}")
    if n_both != PUBLISHED_BOTH:
        print("\n  Note. Every entry carrying a periodicity marker also has an\n"
              "  ascertainable duration, so the intersection recomputes as "
              f"{n_both}\n  against the {PUBLISHED_BOTH} printed in Table 11. "
              "The one-study difference\n  (0.3% of the corpus) affects no other "
              "figure and no statement in\n  the text; it is recorded here rather "
              "than silently reconciled.")

    print(f"\nwrote {OUTPUT}")
    if not ok:
        sys.exit("duration counts diverge from Table 11")


if __name__ == "__main__":
    main()
